### ISSUE TITLE
Control dax_cluster_encryption_at_rest_enabled failing due to un-supported region issue

### ISSUE THREAD

**Issue by bigdatasourav** [turbot/steampipe-mod-aws-compliance#321]
**Describe the bug**

select
-- Required Columns
arn as resource,
case
when sse_description ->> 'Status' = 'ENABLED' then 'ok'
else 'alarm'
end as status,
case
when sse_description ->> 'Status' = 'ENABLED' then title || ' encryption at rest enabled.'
else title || ' encryption at rest not enabled.'
end as reason,
-- Additional Dimensions
region,
account_id
from
aws_dax_cluster;
Error: InvalidParameterValueException: Access Denied to API Version: DAX_V3

**Comment by misraved** [comment]
@bigdatasourav @khushboo9024 We will be handling the region dependency directly in the code of the `aws_dax_cluster` table (https://github.com/turbot/steampipe-plugin-aws/blob/main/aws/table_aws_dax_cluster.go). Closing this PR since it is no longer needed with the expectation that the fix to the table should resolve the issues in the mod.

**Comment by misraved** [comment]
Tracking the above issue here - https://github.com/turbot/steampipe-plugin-aws/issues/782
