### ISSUE TITLE
Join/Combination of queries

### ISSUE THREAD

**Issue by roisec** [turbot/steampipe-mod-aws-compliance#576]
Hi,
Is there an easy option to query multiple queries and verify if they are true?
For example:
check if the combination of 2 queries - steampipe query aws_compliance.query.vpc_security_group_unsued and aws_compliance.query.vpc_security_group_restrict_ingress_ssh_all?

**Comment by roisec** [comment]
@cbruno10 
For example: 

- Security group used and assigned AND allow ingress port for 22 with 0.0.0.0.
- S3 bucket disables block public access AND bucket policy allow *.
- EKS public cluster AND allow 0.0.0.0 with security group

**Comment by cbruno10** [comment]
Hi @roisec , right now you can run queries (or controls that use them) individually and then review the results to see which resources fail which check. 

Most of our checks in the AWS Compliance mod are based off of [AWS Config Managed Rules](https://docs.aws.amazon.com/config/latest/developerguide/evaluate-config_use-managed-rules.html), and then grouped together according to [AWS Audit Manager frameworks](https://docs.aws.amazon.com/audit-manager/latest/userguide/framework-overviews.html). These rules and frameworks will cover a wide variety of checks, but each check is often kept separate from one another.

An alternative is to build a custom set of controls (or mod) that combine some of the queries we have today, which you can then run to meet your requirements. For more information, please see [Writing Controls](https://steampipe.io/docs/mods/writing-controls).

I'm closing this issue since there are no plans on changing our query and control organization at the moment, but if you have any other questions please let us know!
